version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parts
    volumes:
      - /your/mount/point:/var/lib/mysql
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
  invapplication:
    image: ghcr.io/ejach/inventoryapplication:latest
    restart: always
    environment:
      host: db
      webui_host: localhost
      webui_port: 5000
      username: root
      password: root
      db_port: 3306
      db: parts
    ports:
      - "5000:8000"